"use client";

import { useState } from "react";
import type { WeekMetric, MonthMetric } from "@/app/api/metrics/route";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmtMoney(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency", currency: "USD",
    minimumFractionDigits: 2, maximumFractionDigits: 2,
  }).format(n);
}

function fmtMoneyShort(n: number): string {
  const abs = Math.abs(n);
  const sign = n < 0 ? "-" : "";
  if (abs >= 1_000_000) return `${sign}$${(abs / 1_000_000).toFixed(2)}M`;
  if (abs >= 1_000)     return `${sign}$${(abs / 1_000).toFixed(1)}K`;
  return fmtMoney(n);
}

function fmtDate(iso: string): string {
  const [y, m, d] = iso.split("-");
  return `${m}/${d}/${y}`;
}

function fmtRatio(v: number | null): string {
  if (v === null || !isFinite(v)) return "N/A";
  return v.toFixed(2);
}

function fmtPct(n: number): string {
  if (!isFinite(n)) return "—";
  return `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
}

function fmtMonth(ym: string): string {
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  const [y, m] = ym.split("-");
  return `${months[parseInt(m, 10) - 1]} '${y.slice(2)}`;
}

function ratioStatus(v: number | null, good: number, warn: number, higherIsBetter = true): string {
  if (v === null || !isFinite(v)) return "—";
  if (higherIsBetter) {
    if (v >= good) return "●  Good";
    if (v >= warn) return "◑  Caution";
    return "○  Alert";
  } else {
    if (v <= good) return "●  Good";
    if (v <= warn) return "◑  Caution";
    return "○  Alert";
  }
}

// ─── PDF generator ────────────────────────────────────────────────────────────

async function generatePDF(weeks: WeekMetric[], months: MonthMetric[]) {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });

  const navy  = [27, 42, 74]   as [number, number, number];
  const white = [255, 255, 255] as [number, number, number];
  const light = [245, 246, 248] as [number, number, number];
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const today = new Date().toLocaleDateString("en-US");

  const latest = weeks[weeks.length - 1];
  const prior  = weeks.length >= 2 ? weeks[weeks.length - 2] : null;

  // ── Header helper ─────────────────────────────────────────────────────────

  function pageHeader(title: string) {
    doc.setFillColor(...navy);
    doc.rect(0, 0, pageW, 22, "F");
    doc.setTextColor(...white);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Vance Corporation — Weekly Pulse Dashboard", 14, 10);
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.text(title, 14, 17);
    doc.text(`Generated: ${today}`, pageW - 14, 17, { align: "right" });
    doc.setTextColor(30, 30, 30);
  }

  function pageFooter(pageNum: number) {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${pageNum}  ·  Generated by VanceCorp Weekly Pulse`,
      pageW / 2,
      pageH - 8,
      { align: "center" }
    );
  }

  function sectionTitle(text: string, y: number): number {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...navy);
    doc.text(text, 14, y);
    doc.setTextColor(30, 30, 30);
    return y + 5;
  }

  // ── Page 1: Executive Summary ─────────────────────────────────────────────

  pageHeader(`Executive Summary — Week Ending ${fmtDate(latest.week_ending)}`);

  const dataRange =
    weeks.length > 1
      ? `Data range: ${fmtDate(weeks[0].week_ending)} – ${fmtDate(latest.week_ending)} (${weeks.length} weeks)`
      : `Single week: ${fmtDate(latest.week_ending)}`;

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(dataRange, 14, 28);
  doc.setTextColor(30, 30, 30);

  let y = 34;
  y = sectionTitle("Financial Position", y);

  const summaryLines = [
    `Cash on Hand: ${fmtMoney(latest.cash)}${prior ? `  (WoW: ${fmtPct(prior.cash !== 0 ? ((latest.cash - prior.cash) / Math.abs(prior.cash)) * 100 : 0)})` : ""}`,
    `Accounts Receivable: ${fmtMoney(latest.ar)}`,
    `Accounts Payable: ${fmtMoney(latest.ap)}`,
    `Payroll Liabilities: ${fmtMoney(latest.payroll)}`,
    `Net Liquidity (Cash − AP − Payroll): ${fmtMoney(latest.net_liquidity)}`,
    `Total Obligations (AP + Payroll): ${fmtMoney(latest.ap + latest.payroll)}`,
  ];

  doc.setFontSize(9);
  summaryLines.forEach((line) => {
    doc.text(line, 16, y);
    y += 5.5;
  });

  y += 4;
  y = sectionTitle("Key Highlights", y);

  const highlights: string[] = [];
  if (prior) {
    const cashDir = latest.cash > prior.cash ? "increased" : "decreased";
    highlights.push(`• Cash ${cashDir} by ${fmtMoneyShort(Math.abs(latest.cash - prior.cash))} week-over-week.`);
    if (latest.ar_change !== null) {
      if (latest.ar_change <= 0) {
        highlights.push(`• Collected ${fmtMoneyShort(Math.abs(latest.ar_change))} in receivables this week.`);
      } else {
        highlights.push(`• AR grew by ${fmtMoneyShort(latest.ar_change)} — billing outpaced collections.`);
      }
    }
    if (latest.ap_change !== null) {
      const apDir = latest.ap_change <= 0 ? "decreased" : "increased";
      highlights.push(`• Trade payables ${apDir} by ${fmtMoneyShort(Math.abs(latest.ap_change))}.`);
    }
  }
  if (latest.cash_coverage_weeks !== null) {
    highlights.push(`• Cash runway at current burn rate: ${latest.cash_coverage_weeks.toFixed(1)} weeks.`);
  }

  doc.setFontSize(9);
  highlights.forEach((line) => {
    const wrapped = doc.splitTextToSize(line, pageW - 28);
    doc.text(wrapped, 16, y);
    y += wrapped.length * 5.5;
  });

  pageFooter(1);

  // ── Page 2: KPI Snapshot + Ratios ─────────────────────────────────────────

  doc.addPage();
  pageHeader("KPI Snapshot & Financial Ratios");

  const kpiRows = [
    ["Cash on Hand",        fmtMoney(latest.cash),         prior ? fmtPct(prior.cash !== 0 ? ((latest.cash - prior.cash) / Math.abs(prior.cash)) * 100 : 0) : "—", latest.cash >= 0 ? "●  Positive" : "○  Negative"],
    ["Accounts Receivable", fmtMoney(latest.ar),           prior ? (latest.ar_change !== null ? fmtPct((latest.ar_change / (prior.ar || 1)) * 100) : "—") : "—", "—"],
    ["Accounts Payable",    fmtMoney(latest.ap),           prior ? (latest.ap_change !== null ? fmtPct((latest.ap_change / (prior.ap || 1)) * 100) : "—") : "—", "—"],
    ["Payroll Liabilities", fmtMoney(latest.payroll),      "—", "—"],
    ["Net Liquidity",       fmtMoney(latest.net_liquidity), "—", latest.net_liquidity >= 0 ? "●  Positive" : "○  Negative"],
    ["Backlog (All-Time)",  fmtMoney(weeks.reduce((s, w) => s + w.bids_won_value, 0)), "—", "—"],
  ];

  autoTable(doc, {
    startY: 28,
    head: [["Metric", "Current Value", "WoW Change", "Status"]],
    body: kpiRows,
    theme: "striped",
    headStyles: { fillColor: navy, fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 52 },
      1: { halign: "right", cellWidth: 40 },
      2: { halign: "right", cellWidth: 30 },
      3: { cellWidth: 35 },
    },
    margin: { left: 14, right: 14 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const kpiEndY = (doc as any).lastAutoTable.finalY + 8;

  const ratioRows = [
    ["Current Ratio",    fmtRatio(latest.current_ratio),       prior ? fmtRatio(prior.current_ratio)       : "—",
      ratioStatus(latest.current_ratio, 1.5, 1.0)],
    ["Quick Ratio",      fmtRatio(latest.quick_ratio),         prior ? fmtRatio(prior.quick_ratio)         : "—",
      ratioStatus(latest.quick_ratio, 0.5, 0.25)],
    ["AR / AP",          fmtRatio(latest.ar_to_ap),            prior ? fmtRatio(prior.ar_to_ap)            : "—",
      ratioStatus(latest.ar_to_ap, 1.2, 0.8)],
    ["Cash Coverage",    latest.cash_coverage_weeks !== null ? `${latest.cash_coverage_weeks.toFixed(1)} wks` : "N/A",
      prior?.cash_coverage_weeks != null ? `${prior.cash_coverage_weeks.toFixed(1)} wks` : "—",
      ratioStatus(latest.cash_coverage_weeks, 8, 4)],
    ["Payroll Coverage", latest.payroll_coverage !== null ? `${latest.payroll_coverage.toFixed(1)} wks` : "N/A",
      prior?.payroll_coverage != null ? `${prior.payroll_coverage.toFixed(1)} wks` : "—",
      ratioStatus(latest.payroll_coverage, 8, 4)],
  ];

  sectionTitle("Financial Health Ratios", kpiEndY);

  autoTable(doc, {
    startY: kpiEndY + 5,
    head: [["Ratio", "Current", "Prior Week", "Status"]],
    body: ratioRows,
    theme: "striped",
    headStyles: { fillColor: navy, fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 52 },
      1: { halign: "right", cellWidth: 30 },
      2: { halign: "right", cellWidth: 30 },
      3: { cellWidth: 35 },
    },
    margin: { left: 14, right: 14 },
  });

  pageFooter(2);

  // ── Page 3: Category Balances by Week ─────────────────────────────────────

  doc.addPage();
  pageHeader("Category Balances — All Weeks");

  const balBody = weeks.map((w) => [
    fmtDate(w.week_ending),
    fmtMoney(w.cash),
    fmtMoney(w.ar),
    fmtMoney(w.ap),
    fmtMoney(w.payroll),
    fmtMoney(w.net_position),
  ]);

  autoTable(doc, {
    startY: 28,
    head: [["Week Ending", "Cash", "AR", "AP", "Payroll", "Net Position"]],
    body: balBody,
    theme: "striped",
    headStyles: { fillColor: navy, fontSize: 8.5 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 24 },
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right", fontStyle: "bold" },
    },
    margin: { left: 14, right: 14 },
  });

  pageFooter(3);

  // ── Page 4: Monthly Summary ────────────────────────────────────────────────

  if (months.length > 0) {
    doc.addPage();
    pageHeader("Monthly Summary");

    const monthBody = months.map((m) => [
      fmtMonth(m.month),
      fmtMoney(m.avg_cash),
      fmtMoney(m.avg_ar),
      fmtMoney(m.avg_ap),
      fmtMoney(m.avg_payroll),
      fmtMoney(m.avg_net_position),
      m.win_rate_pct > 0 ? `${m.win_rate_pct.toFixed(1)}%` : "N/A",
    ]);

    autoTable(doc, {
      startY: 28,
      head: [["Month", "Avg Cash", "Avg AR", "Avg AP", "Avg Payroll", "Avg Net", "Win Rate"]],
      body: monthBody,
      theme: "striped",
      headStyles: { fillColor: navy, fontSize: 8.5 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
        4: { halign: "right" },
        5: { halign: "right", fontStyle: "bold" },
        6: { halign: "right" },
      },
      margin: { left: 14, right: 14 },
    });

    pageFooter(4);
  }

  // ── Page 5: Bid Activity (if any) ─────────────────────────────────────────

  const hasBids = weeks.some((w) => w.bids_submitted_count > 0 || w.bids_submitted_value > 0);
  if (hasBids) {
    doc.addPage();
    const pg = months.length > 0 ? 5 : 4;
    pageHeader("Bid Activity — Weekly");

    const bidBody = weeks
      .filter((w) => w.bids_submitted_count > 0 || w.bids_submitted_value > 0)
      .map((w) => {
        const winRate =
          w.bids_submitted_count > 0
            ? ((w.bids_won_count / w.bids_submitted_count) * 100).toFixed(1) + "%"
            : "—";
        return [
          fmtDate(w.week_ending),
          String(w.bids_submitted_count),
          fmtMoney(w.bids_submitted_value),
          String(w.bids_won_count),
          fmtMoney(w.bids_won_value),
          winRate,
        ];
      });

    autoTable(doc, {
      startY: 28,
      head: [["Week", "Sub Count", "Sub Value", "Won Count", "Won Value", "Win Rate"]],
      body: bidBody,
      theme: "striped",
      headStyles: { fillColor: navy, fontSize: 8.5 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 24 },
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
        4: { halign: "right" },
        5: { halign: "right" },
      },
      margin: { left: 14, right: 14 },
    });

    pageFooter(pg);
  }

  // ── Save ──────────────────────────────────────────────────────────────────

  const dateStr = latest.week_ending;
  doc.save(`Vance_Dashboard_Report_${dateStr}.pdf`);
}

// ─── Button Component ─────────────────────────────────────────────────────────

export default function DashboardPDF({
  weeks,
  months,
}: {
  weeks: WeekMetric[];
  months: MonthMetric[];
}) {
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);
    try {
      await generatePDF(weeks, months);
    } catch (e) {
      console.error("Dashboard PDF export failed:", e);
      alert("PDF export failed. See console for details.");
    } finally {
      setExporting(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting || weeks.length === 0}
      className="btn-secondary flex items-center gap-2 disabled:opacity-50"
    >
      {exporting ? (
        <>
          <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
          </svg>
          Generating PDF…
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Export PDF
        </>
      )}
    </button>
  );
}
